title: Sangyeon Cho
email: csymhph@snu.ac.kr
description: Personal academic homepage of Sangyeon Cho, focused on causal inference, conformal prediction, and explainable AI.
theme: minima
url: "https://csymhph.github.io"
baseurl: ""
name: Sangyeon Cho
job: Master's Student
location: Seoul, Republic of Korea
github_username: csymhph
# Build Settings
markdown: kramdown
# remote_theme: "mmistakes/minimal-mistakes"
# plugins:
#   - jekyll-include-cache
permalink: pretty

header_pages:
  - publications.md
  - blog.md
  - hobbies.md
